config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to:'pages#home'
  devise_for :users, controllers: { registrations: 'users/registrations' }
  resources :users do
    resource :profile
  end
  get 'about', to: 'pages#about'
  resources :contacts, only: :create
  get 'contact-us', to: 'contacts#new', as: 'new_contact'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  # Contact form validations
  validates :name, presence: true
  validates :email, presence: true
  validates :comments, presence: true
end

app/models/plan.rb
class Plan < ActiveRecord::Base
  has_many :users
end

app/models/profile.rb
class Profile < ActiveRecord::Base
  belongs_to :user
  has_attached_file :avatar,
                    :styles => { :medium => "300x300", :thumb => "100x100", :icon => "32x32" },
                    :default_url => "/images/:style/missing.png"
  validates_attachment_content_type :avatar, :content_type => /\Aimage\/.*\Z/
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  belongs_to :plan
  has_one :profile
  
  attr_accessor :stripe_card_token
  # If Pro user passes validations (email, password, etc.)
  # then call Stripe and tell Stripe to set up a subscription
  # upon chargin the customer's card.
  # Stripe responds back with cutomer data.
  # Store customer.id as the customer token and save the user.
  
  def save_with_subscription
    if valid?
     customer = Stripe::Customer.create(description: email, plan: plan_id, card: stripe_card_token)
     self.stripe_customer_token = customer.id
     save!
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  
  # Whitelist the following form fields so that we can process them
  # if coming from a devise sign up form
  before_action :configure_permitted_parameters, if: :devise_controller?
  
  protected
    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:stripe_card_token, :email, :password, :password_confirmation) }
    end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  
  
  # GET request to /contact-us
  # Show new contact form
  def new
    @contact = Contact.new
  end
  
  # POST request /contacts
  def create
    # Mass assignment of form fields into Contact object
    @contact = Contact.new(contact_params)
    # Save the Contact object to the database
    if @contact.save
      # Store form fields via parameters, into variables
      name = params[:contact][:name]
      email = params[:contact][:email]
      body = params[:contact][:comments]
      # Plug variable into Contact Mailer
      # email method and send email
      ContactMailer.contact_email(name, email, body).deliver
      # Store success message in flash hash
      # and redirect to the new action
      flash[:success] = "Message sent."
      redirect_to new_contact_path
    else
      # If Contact object doesn't save,
      # store errors in error hash
      # redirect to the new action
      flash[:danger] = @contact.errors.full_messages.join(", ")
      redirect_to new_contact_path
    end
  end
  
  private
  # To collect data from form, we need to use
  # strong parameters and whitelist the form fields
    def contact_params
      params.require(:contact).permit(:name, :email, :comments)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  #GET request for / which is our home page
  def home
    @basic_plan = Plan.find(1)
    @pro_plan = Plan.find(2)
  end
  
  def about
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :only_current_user
  
  # GET to /users/:user_id/profile/new
  def new
    # Render blank profile details form
    @profile = Profile.new
  end
  
  # POST to /users/:user_id/profile
  def create
    # Ensure that we have the user who is filling out form
    @user = User.find( params[:user_id] )
    # Create profile linked to this specifc user
    @profile = @user.build_profile( profile_params )
    if @profile.save
      flash[:success] = "Profile Updated!"
      redirect_to user_path(id: params[:user_id] )
    else
      render action: :new
    end
  end
  
  # GET to /users/:user_id/profile/edit
  def edit
    @user = User.find( params[:user_id] )
    @profile = @user.profile
  end
  
  # PUT to /users/:user_id/profile
  def update
    # Retrieve user who is filling out form from database
    @user = User.find( params[:user_id] )
    # Retrieve that users profile
    @profile = @user.profile
    # Mass assign profile attributes and save (update)
    if @profile.update_attributes(profile_params)
      flash[:success] = "Profile updated!"
      redirect_to user_path( params[:user_id] )
    else
      render action: :edit
    end
      
  end
  
  private
    def profile_params
      params.require(:profile).permit(:first_name, :last_name, :avatar, :company, :job_title, :phone_number, :email, :description)  
    end
    
    def only_current_user
      @user = User.find( params[:user_id] )
      redirect_to(root_url) unless @user == current_user
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_action :select_plan, only: :new
 
  # Extend default Devise gem behavior so that
  # users signing up with the Pro account (plan ID 2)
  # save with a special Stripe subscription function.
  # Otherwise Devise signs up user as usual.
  def create
    super do |resource|
      if params[:plan]
        resource.plan_id = params[:plan]
        if resource.plan_id == 2
          resource.save_with_subscription
        else
          resource.save
        end
      end
    end
  end
  
  private
  def select_plan
    unless (params[:plan] == '1' || params[:plan] == '2')
      flash[:notice] = "Please select a membership plan to sign up."
      redirect_to root_url
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
   before_action :authenticate_user!
   
   def index
      @users = User.includes(:profile)
   end
   
   # GET to /users/:id
   def show
      @user = User.find( params[:id] )
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/contacts/new.html.erb
<body class="bg-color">
  <div class="container new-page">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <div class = 'well'>
          <h2 class="text-center form-title">Contact Us</h2>
          <%= form_for @contact do |f| %>
          <div class="form-group">
            <%= f.label :name %>
            <%= f.text_field :name, class: 'form-control' %>
          </div>
          <div class="form-group">  
            <%= f.label :email %>
            <%= f.text_field :email, class: 'form-control' %>
          </div>
          <div class="form-group">
            <%= f.label :comments %>
            <%= f.text_area :comments, class: 'form-control' %>
          </div>
            <%= f.submit 'Submit', class: 'btn btn-success' %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Churn.io</title>
    <%= csrf_meta_tags %>
    <link href="//fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
    <link href="css/simple-sidebar.css.scss" rel="stylesheet">
    <link href="css/bootstrap_and_overrides.css.scss" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag "https://js.stripe.com/v2/", type: 'text/javascript' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
  </head>

  <body>
    <div id="wrapper">
    <!-- Sidebar -->
      <% if user_signed_in? %>
        <div id="sidebar-wrapper">
            <ul class="sidebar-nav">
                <li class="sidebar-brand">
                    <%= link_to "Home", root_path %>
                </li>
                <li>
                    <a href=""><i class="fa fa-upload"></i>&nbsp; Import</a>
                </li>
                <li>
                    <a href="#"><i class="fa fa-pencil-square-o"></i>&nbsp; Contact</a>
                </li>
            </ul>
        </div>
      <% end %>
        <!-- /#sidebar-wrapper -->
        
        <!-- Page Content -->
        <nav class="navbar navbar-default navbar-fixed-top">
          <div class="container-fluid">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
                <% if user_signed_in? %>
                <a class="navbar-brand title-brand" href="#menu-toggle" id="menu-toggle"><i class="fa fa-bars"></i></a>
                <% end %>
                <%= link_to root_path, class: "navbar-brand title-brand" do %>
                  Churn.io
                <% end %>
            </div>
           
        
            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
              <ul class="nav navbar-nav navbar-left">
                <li><%= link_to "About", about_path %></li>
                <li><%= link_to "Contact Us", new_contact_path %></li>
              </ul>
              <ul class="nav navbar-nav navbar-right">
                    <% if user_signed_in? %>
                      <li class="dropdown">
                        <% if current_user.profile %>
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= image_tag current_user.profile.avatar.url(:icon), class: 'avatar-icon img-circle' %> <%= current_user.profile.first_name %> <%= current_user.profile.last_name %><span class="caret"></span></a>
                        <% else %>
                          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Guest<span class="caret"></span></a>
                        <% end %>
                        <ul class="dropdown-menu">
                          <% if current_user.profile %>
                            <li><%= link_to "Manage account", edit_user_registration_path %></li>
                            <li><%= link_to "View your profile", user_path(id: current_user.id) %></li>
                            <li><%= link_to "Edit your profile", edit_user_profile_path(user_id: current_user.id) %></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "View the community", users_path %></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                          <% else %>
                            <li><%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id) %></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "View the community", users_path %></li>
                            <li role="separator" class="divider"></li>
                            <li><%= link_to "Sign Out", destroy_user_session_path, method: :delete %></li>
                          <% end %>   
                        </ul>
                        
                      </li>
                    <% else %>
                      <li><%= link_to "Sign In", new_user_session_path %> </li>
                      <li><%#= link_to "Sign Up", new_user_registration_path %></li>
                    <% end %>
              </ul>
            </div><!-- /.navbar-collapse -->
          </div><!-- /.container-fluid -->
        </nav>
        
        <div class="page-container">
          <div class="container flash-container">
            <% flash.each do |type, msg| %>
              <%= content_tag :div, msg, class: "alert alert-#{type}" %>
            <% end %>
          </div>
          <%= yield %>
        </div>
        
        <!-- /#sidebar-wrapper -->
        
      </div>
    <!-- /#wrapper -->
    
    <!-- jQuery -->
    <script src="js/jquery.js"></script>

    <!-- Bootstrap Core JavaScript -->
    <script src="js/bootstrap.min.js"></script>

    <!-- Menu Toggle Script -->
    <script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
    </script>
  </body>
</html>

app/views/pages/about.html.erb
<body class="bg-color">
  <div class="about-page">
      <h1>About Churn.io</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Dignissimos, veritatis, quia repellendus nemo laudantium soluta voluptate suscipit sequi dicta amet. Accusantium eveniet fugit voluptatibus ea neque quia soluta consequuntur autem.</p>
  </div>
</body>

app/views/pages/home.html.erb
<% if user_signed_in? %>
  <body>
    <div class="container new-page">
      <div class="row">
        <div class="col-md-6 col-md-offset-3">
          <div class="well">
            <h2 class="text-center">Create your URL!</h2>
            <% if current_user.profile %>
              <%#= link_to "Edit your profile", '#', class: 'btn btn-default btn-lg btn-block' %>
              <%#= link_to "View your profile", user_path(current_user.id), class: 'btn btn-default btn-lg btn-block' %>
            <% else %>
              <%= link_to "Create your profile", new_user_profile_path(user_id: current_user.id),  class: 'btn btn-default btn-lg btn-block' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </body>
<% else %>
  <body class="bg-color">
    <div class="row">
      <div class="container">
        <div class="row home-title ">
          <h1 class="title font-cursive">Churn.io</h1>
          <h2 class="callout">Data hygiene, delivered.</h2>
        </div>
        <div class="container home-signup-links">
          <div class="col-md-3 col-md-offset-3">
            <div class="well">
              <h2 class="text-center">Basic Membership</h2>
              <%= link_to "Sign up with Basic", new_user_registration_path(plan: @basic_plan.id), class: 'btn btn-primary btn-lg btn-block' %>
            </div>
          </div>
          <div class="col-md-3">
            <div class="well">
              <h2 class="text-center">Pro Membership</h2>
              <%= link_to "Sign up with Pro", new_user_registration_path(plan: @pro_plan.id), class: 'btn btn-success btn-lg btn-block' %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </body>
<% end %>
  

app/views/profiles/_form.html.erb
<%= form_for @profile, url: user_profile_path, :html => { :multipart => true } do |f| %>
  <div class="form-group">
    <%= f.label :first_name %>
    <%= f.text_field :first_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :last_name %>
    <%= f.text_field :last_name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :avatar %>
    <%= f.file_field :avatar, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :company %>
    <%= f.text_field :company, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :job_title %>
    <%= f.select :job_title, ['Sales', 'Marketing', 'IT'], {}, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :phone_number %>
    <%= f.text_field :phone_number, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :email %>
    <%= f.text_field :email, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %>
    <%= f.text_area :description, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit "Update Profile", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/profiles/edit.html.erb
<body class="bg-color">
  <div class="container new-page"> 
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well page-container">
          <div class="text-center">
            <h1>Edit your profile</h1>
          </div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/profiles/new.html.erb
<body class="bg-color">
  <div class="container new-page"> 
    <div class="row">
      <div class="col-md-6 col-md-offset-3">
        <div class="well page-container">
          <div class="text-center">
            <h1>Create your profile</h1>
            <p>Join the Param Pro community</p>
          </div>
          <%= render 'form' %>
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/index.html.erb
<body>
  <div class="new-page">
    <div class="container">
      <div class="row">
        <div class="col-md-8 col-md-offset-2">
          <h1 class="text-center">The Churn Community</h1>
          <p class="text-center">Welcome to the Churn community. Users must fill out a profile in order to be visible.</p></br>
          <ul class="list-unstyled">
            <% @users.each do |user| %>
              <% if user.profile %>
                <li>
                  <div class="row well <%= cycle('white-bg', '') %>">
                    <div class="col-md-4 text-centered">
                      <% if user.profile.avatar %>
                        <%= link_to user do %>
                          <%= image_tag user.profile.avatar.url, class: 'index-icon' %>
                        <% end %>
                      <% end %>
                    </div>
                    <div>
                      <%= link_to user do %>
                        <h2> <%= user.profile.first_name %> <%= user.profile.last_name %></h2>
                      <% end %>
                      <p>
                        <%= user.profile.job_title %>
                        <% if user.plan_id == 2 %>
                          <span class="label label-danger">PRO</span>
                        <% end %>
                      </p>
                    </div>
                  </div>
                </li>
              <% end %>
            <% end %>
          </ul> 
        </div>
      </div>
    </div>
  </div>
</body>

app/views/users/show.html.erb
<body class="bg-color">
  <div class="container new-page"> 
    <div class="row">
      <div class="col-md-8 col-md-offset-2">
        <div class="well page-container">
          <div class="text-center">
          <%= image_tag @user.profile.avatar.url, class: 'avatar-show-img img-circle' %><br/>
          <%= @user.profile.first_name %> <%= @user.profile.last_name %><br/>
          <%= @user.profile.job_title %><br/>
          <% if true #current_user.plan_id == 2 %>
            <%= @user.profile.phone_number %><br/>
            <%= @user.profile.email %><br/>
          <% end %>
          <%= @user.profile.description %>
          </div>
        </div>
      </div>
    </div>
  </div>
</body>